### ISSUE TITLE
It doesn't work on Meizu MX2

### ISSUE THREAD

**Issue by FunnyDevs** [justasm/WindowView#1]
Hello! I was trying your library but i it seems that the sensor event doesn't work. I tried also your sample app. Thanks

**Comment by justasm** [comment]
Hi, thanks for bringing this to attention.

However, I can do little to help identify the issue with the provided information. Some useful information to have would include:
- device model / name
- Android OS version
- development environment
  - Android Studio version
  - build tools version
  - compile SDK version
  - target SDK version
- XML layout containing WindowView
- any code interacting with WindowView
- any errors printed to LogCat, if applicable

**Comment by FunnyDevs** [comment]
I think that, overall, is useless give you all this information because even your sample app doesn't work, so isn't a problem about my code. I have a meizu mx2 with Android 5.0.1, and Android Studio 1.3.2

**Comment by justasm** [comment]
I ask because the project files had not been kept up to date with the latest Android Studio (I have since fixed this after you raising this issue).

I know the sample app to work on both the LG Nexus 5 and the LG GT540, so I'm trying to narrow down the issue.

The Meizu MX2 has a gyro, compass and accelerometer so it should be fully capable. Can you verify whether other apps that use motion sensor data work on your phone?

**Comment by justasm** [comment]
It would also be useful to know if, running the sample app and turning on "Debug Tilt" in the overflow menu, you see yaw / pitch / roll values that are changing when you move the device.

**Comment by FunnyDevs** [comment]
I'm trying it on Moto G 2014 and it works. 
On Meizu mx2 turning on "debug tilt" nothing happens on values. I used "Motion" library apk sample (https://github.com/nvanbenschoten/motion) on Meizu and it works, so i have problem only with your library :(

**Comment by justasm** [comment]
Thanks for the update.

I wasn't previously aware of the "Motion" library, which seems to be providing essentially the same functionality as WindowView. It uses a different fused sensor, `TYPE_ROTATION_VECTOR`, which is so far the likeliest reason why the behavior on your Meizu MX2 differs, although it is very unusual (I thought impossible?) that a device supports `TYPE_ROTATION_VECTOR` but does not provide `TYPE_MAGNETIC_FIELD` + `TYPE_GRAVITY` and/or `TYPE_ACCELEROMETER`, which is what WindowView uses.

Updating WindowView to use `TYPE_ROTATION_VECTOR` had been in the plans, but interest in the project seemed low and I never got around to it. I may experiment with it this weekend, although at this point is there any reason you are interested in WindowView instead of using "Motion"?

**Comment by FunnyDevs** [comment]
I would obtain the same effect of the facebook app Paper 
http://subjc.com/facebook-paper-photo-panner/

I have tried motion but i prefer the easiness of your library even because with WindowView i can put a photo in CenterCrop.

**Comment by justasm** [comment]
OK, I will aim to update WindowView by tomorrow and hopefully you can then confirm whether using the `TYPE_ROTATION_VECTOR` fused sensor fixes the issue.

**Comment by FunnyDevs** [comment]
Ok, Thanks a lot!!

**Comment by justasm** [comment]
Please take a look and see if the latest version of the project has fixed
your issue with the MX2. If not, we will have to investigate further.

**Comment by FunnyDevs** [comment]
Now it works!!! Thanks a lot for all!!!

**Comment by justasm** [comment]
Great, thanks for testing!
